$mousemode_enabled = 1

exec = echo 1 > ~/.config/hypr/toggles/mousemode.state
exec = ~/.config/hypr/toggles/mousemode/start.sh

bind = ,mouse:274, exec, "$HOME/.config/hypr/toggles/mousemode/show.sh"
bindrtlupn = ,mouse:274, exec, "$HOME/.config/hypr/toggles/mousemode/release.sh"
bindn = ,mouse:272, exec, "$HOME/.config/hypr/toggles/mousemode/left_click.sh"
