source = ~/.config/hypr/toggles/scrolling.conf
source = ~/.config/hypr/toggles/focusfit.conf
source = ~/.config/hypr/toggles/mousemode.conf

bind = $mainMod SHIFT, O, exec, ~/.config/hypr/toggles/toggle.sh scrolling $scrolling_enabled
bind = $mainMod SHIFT, B, exec, ~/.config/hypr/toggles/toggle.sh focusfit $focusfit_enabled
 
